development:
  clients:
    default:
      database: trigger_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  clients:
    default:
      database: trigger_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
     uri: <%= ENV['MONGO_URI'] %>
     options:
       connect_timeout: 15
